### ISSUE TITLE
Replace all GIFs with Static Images

### ISSUE THREAD

**Issue by dannydeezy** [dannydeezy/bitcoin-book#2]
GIFs will not work on a real book, so we should replace all the GIFs with static images. 

For each one, we can do one of the following:

- Screenshot the actual GIF (as long as you can get it to look nice)

- Replace GIF with a static image that has a similar theme

**Comment by Zero-1729** [comment]
@dannydeezy I initially included them as embedded links that displayed the GIFs when connected to the Internet, but I ended up doing a mixture of both your suggestions.

I used **ffmpeg** to extract the frames for each GIF (which preserved the resolution) and replaced each GIF with the most appropriate of its frames.

These static GIFs are all included in the '`images/`' folder I created, along with the other static images you originally had in the threads.
